import { ApiStatus, ApiSummaryCountry } from './types';

export const STATUSES: ApiStatus[] = ['confirmed', 'deaths', 'recovered'];

// avoid cursor touching tooltip
export const TOOLTIP_OFFSET = 4;

// map ISO country codes to CDS country names
// https://en.wikipedia.org/wiki/ISO_3166-1
export const COUNTRIES = {
  ASM: 'American Samoa',
  GUM: 'Guam',
  MNP: 'Northern Mariana Islands',
  PRI: 'Puerto Rico',
  VIR: 'United States Virgin Islands',
  USA: 'United States',
  AFG: 'Afghanistan',
  ALB: 'Albania',
  DZA: 'Algeria',
  AND: 'Andorra',
  AGO: 'Angola',
  ATG: 'Antigua and Barbuda',
  ARG: 'Argentina',
  ARM: 'Armenia',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BHS: 'The Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BEN: 'Benin',
  BTN: 'Bhutan',
  BOL: 'Bolivia',
  BIH: 'Bosnia and Herzegovina',
  BRA: 'Brazil',
  BRN: 'Brunei',
  BGR: 'Bulgaria',
  BFA: 'Burkina Faso',
  CPV: 'Cape Verde',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CAF: 'Central African Republic',
  TCD: 'Chad',
  CHL: 'Chile',
  CHN: 'China',
  HKG: 'Hong Kong',
  MAC: 'Macau',
  COL: 'Colombia',
  COG: 'Congo-Brazzaville',
  COD: 'Democratic Republic of the Congo',
  CRI: 'Costa Rica',
  CIV: "Côte d'Ivoire",
  HRV: 'Croatia',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  GRL: 'Greenland',
  DNK: 'Denmark',
  DJI: 'Djibouti',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  SLV: 'El Salvador',
  GNQ: 'Equatorial Guinea',
  ERI: 'Eritrea',
  EST: 'Estonia',
  SWZ: 'Eswatini',
  ETH: 'Ethiopia',
  FJI: 'Fiji',
  FIN: 'Finland',
  FRA: 'France',
  GAB: 'Gabon',
  GMB: 'The Gambia',
  GEO: 'Georgia',
  DEU: 'Germany',
  GHA: 'Ghana',
  GRC: 'Greece',
  GTM: 'Guatemala',
  GIN: 'Guinea',
  GUY: 'Guyana',
  HTI: 'Haiti',
  VAT: 'Vatican City',
  HND: 'Honduras',
  HUN: 'Hungary',
  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  ISR: 'Israel',
  JAM: 'Jamaica',
  JPN: 'Japan',
  JOR: 'Jordan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KOR: 'South Korea',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LBR: 'Liberia',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MDG: 'Madagascar',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLT: 'Malta',
  MRT: 'Mauritania',
  MUS: 'Mauritius',
  MEX: 'Mexico',
  MDA: 'Moldova',
  MCO: 'Monaco',
  MNG: 'Mongolia',
  MNE: 'Montenegro',
  MAR: 'Morocco',
  NAM: 'Namibia',
  NPL: 'Nepal',
  NLD: 'Netherlands',
  NZL: 'New Zealand',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  MKD: 'North Macedonia',
  NOR: 'Norway',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PAN: 'Panama',
  PNG: 'Papua New Guinea',
  PRY: 'Paraguay',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRT: 'Portugal',
  QAT: 'Qatar',
  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',
  LCA: 'Saint Lucia',
  VCT: 'Saint Vincent and the Grenadines',
  SMR: 'San Marino',
  SAU: 'Saudi Arabia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SYC: 'Seychelles',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SOM: 'Somalia',
  ZAF: 'South Africa',
  ESP: 'Spain',
  LKA: 'Sri Lanka',
  SDN: 'Sudan',
  SUR: 'Suriname',
  SWE: 'Sweden',
  CHE: 'Switzerland',
  TWN: 'Taiwan',
  TZA: 'Tanzania',
  THA: 'Thailand',
  TGO: 'Togo',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  ARE: 'United Arab Emirates',
  GBR: 'United Kingdom',
  URY: 'Uruguay',
  UZB: 'Uzbekistan',
  VEN: 'Venezuela',
  VNM: 'Vietnam',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
  DMA: 'Dominica',
  GRD: 'Grenada',
  MOZ: 'Mozambique',
  SYR: 'Syria',
  TLS: 'East Timor',
  BLZ: 'Belize',
  LAO: 'Laos',
  LBY: 'Libya',
  PSE: 'Palestinian Territories',
  GNB: 'Guinea-Bissau',
  MLI: 'Mali',
  KNA: 'Saint Kitts and Nevis',
  MMR: 'Myanmar',
  BWA: 'Botswana',
  BDI: 'Burundi',
  SLE: 'Sierra Leone',
  ESH: 'Sahrawi Arab Democratic Republic',
  ITA: 'Italy',
};
