import { ApiStatus } from './types';

// eslint-disable-next-line import/prefer-default-export
export const STATUSES: ApiStatus[] = ['confirmed', 'deaths', 'recovered'];

export const COUNTRIES = {
  afghanistan: 'Afghanistan',
  albania: 'Albania',
  algeria: 'Algeria',
  andorra: 'Andorra',
  'antigua-and-barbuda': 'Antigua and Barbuda',
  argentina: 'Argentina',
  armenia: 'Armenia',
  aruba: 'Aruba',
  australia: 'Australia',
  austria: 'Austria',
  azerbaijan: 'Azerbaijan',
  bahrain: 'Bahrain',
  bangladesh: 'Bangladesh',
  barbados: 'Barbados',
  belarus: 'Belarus',
  belgium: 'Belgium',
  benin: 'Benin',
  bhutan: 'Bhutan',
  bolivia: 'Bolivia',
  'bosnia-and-herzegovina': 'Bosnia and Herzegovina',
  brazil: 'Brazil',
  brunei: 'Brunei',
  bulgaria: 'Bulgaria',
  'burkina-faso': 'Burkina Faso',
  cambodia: 'Cambodia',
  cameroon: 'Cameroon',
  canada: 'Canada',
  'central-african-republic': 'Central African Republic',
  chile: 'Chile',
  china: 'China',
  colombia: 'Colombia',
  'congo-(brazzaville)': 'Congo (Brazzaville)',
  'congo-(kinshasa)': 'Congo (Kinshasa)',
  'costa-rica': 'Costa Rica',
  'cote-divoire': "Cote d'Ivoire",
  croatia: 'Croatia',
  'cruise-ship': 'Cruise Ship',
  cuba: 'Cuba',
  cyprus: 'Cyprus',
  czechia: 'Czechia',
  denmark: 'Denmark',
  djibouti: 'Djibouti',
  'dominican-republic': 'Dominican Republic',
  ecuador: 'Ecuador',
  egypt: 'Egypt',
  'equatorial-guinea': 'Equatorial Guinea',
  estonia: 'Estonia',
  eswatini: 'Eswatini',
  ethiopia: 'Ethiopia',
  finland: 'Finland',
  france: 'France',
  'french-guiana': 'French Guiana',
  gabon: 'Gabon',
  'gambia,-the': 'Gambia, The',
  georgia: 'Georgia',
  germany: 'Germany',
  ghana: 'Ghana',
  greece: 'Greece',
  greenland: 'Greenland',
  guadeloupe: 'Guadeloupe',
  guam: 'Guam',
  guatemala: 'Guatemala',
  guernsey: 'Guernsey',
  guinea: 'Guinea',
  guyana: 'Guyana',
  'holy-see': 'Holy See',
  honduras: 'Honduras',
  hungary: 'Hungary',
  iceland: 'Iceland',
  india: 'India',
  indonesia: 'Indonesia',
  iran: 'Iran',
  iraq: 'Iraq',
  ireland: 'Ireland',
  israel: 'Israel',
  italy: 'Italy',
  jamaica: 'Jamaica',
  japan: 'Japan',
  jersey: 'Jersey',
  jordan: 'Jordan',
  kazakhstan: 'Kazakhstan',
  kenya: 'Kenya',
  'korea,-south': 'Korea, South',
  kosovo: 'Kosovo',
  kuwait: 'Kuwait',
  kyrgyzstan: 'Kyrgyzstan',
  latvia: 'Latvia',
  lebanon: 'Lebanon',
  liberia: 'Liberia',
  liechtenstein: 'Liechtenstein',
  lithuania: 'Lithuania',
  luxembourg: 'Luxembourg',
  malaysia: 'Malaysia',
  maldives: 'Maldives',
  malta: 'Malta',
  martinique: 'Martinique',
  mauritania: 'Mauritania',
  mauritius: 'Mauritius',
  mayotte: 'Mayotte',
  mexico: 'Mexico',
  moldova: 'Moldova',
  monaco: 'Monaco',
  mongolia: 'Mongolia',
  montenegro: 'Montenegro',
  morocco: 'Morocco',
  namibia: 'Namibia',
  nepal: 'Nepal',
  netherlands: 'Netherlands',
  'new-zealand': 'New Zealand',
  nigeria: 'Nigeria',
  'north-macedonia': 'North Macedonia',
  norway: 'Norway',
  'occupied-palestinian-territory': 'occupied Palestinian territory',
  oman: 'Oman',
  pakistan: 'Pakistan',
  panama: 'Panama',
  paraguay: 'Paraguay',
  peru: 'Peru',
  philippines: 'Philippines',
  poland: 'Poland',
  portugal: 'Portugal',
  'puerto-rico': 'Puerto Rico',
  qatar: 'Qatar',
  'republic-of-the-congo': 'Republic of the Congo',
  reunion: 'Reunion',
  romania: 'Romania',
  russia: 'Russia',
  rwanda: 'Rwanda',
  'saint-lucia': 'Saint Lucia',
  'saint-vincent-and-the-grenadines': 'Saint Vincent and the Grenadines',
  'san-marino': 'San Marino',
  'saudi-arabia': 'Saudi Arabia',
  senegal: 'Senegal',
  serbia: 'Serbia',
  seychelles: 'Seychelles',
  singapore: 'Singapore',
  slovakia: 'Slovakia',
  slovenia: 'Slovenia',
  somalia: 'Somalia',
  'south-africa': 'South Africa',
  spain: 'Spain',
  'sri-lanka': 'Sri Lanka',
  sudan: 'Sudan',
  suriname: 'Suriname',
  sweden: 'Sweden',
  switzerland: 'Switzerland',
  'taiwan*': 'Taiwan*',
  tanzania: 'Tanzania',
  thailand: 'Thailand',
  'the-bahamas': 'The Bahamas',
  'the-gambia': 'The Gambia',
  togo: 'Togo',
  'trinidad-and-tobago': 'Trinidad and Tobago',
  tunisia: 'Tunisia',
  turkey: 'Turkey',
  ukraine: 'Ukraine',
  'united-arab-emirates': 'United Arab Emirates',
  'united-kingdom': 'United Kingdom',
  uruguay: 'Uruguay',
  us: 'US',
  uzbekistan: 'Uzbekistan',
  venezuela: 'Venezuela',
  vietnam: 'Vietnam',
  zambia: 'Zambia',
};
